export const MIN_PASSWORD_LENGTH = 6;
export const SIGNUP_MIN_PASSWORD_LENGTH = MIN_PASSWORD_LENGTH;
export const PASSWORD_CHANGE_MIN_PASSWORD_LENGTH = MIN_PASSWORD_LENGTH;
export const MAX_PASSWORD_LENGTH = 72;
